### ISSUE TITLE
Weird issue relating cat and pids

### ISSUE THREAD

**Issue by Nixtren** [sayem314/Caddy-Web-Server-Installer#9]
``` sh
root@debian:~# caddy start
cat: /var/run/caddy/caddy.pid: No such file or directory

  Starting Caddy Web Server...  DONE

root@debian:~# caddy

  Caddy Web Server is NOT running

  Welcome!
  run caddy help  for help

```

I found this command in the source-code to get Caddy's pid's I guess, here's the output:

``` sh
root@debian:~# ps aux | grep /opt/caddyserver/caddy | grep -v grep | awk '{ print $2 }' | sort -
20014
20017
```

The script doesn't detect Caddy is running, but the pidfile exists and that command returns two pids. And btw, shouldn't the cat error message be silenced/omitted? 

I'm running Debian 8 (Jessie). Anyone with the same problem?

``` sh
root@debian:~# uname -a
Linux debian 2.6.32-042stab113.17 #1 SMP Wed Feb 10 18:31:00 MSK 2016 x86_64 GNU/Linux
```

**Comment by sayem314** [comment]
Should be fixed now!
run this `wget -q https://raw.githubusercontent.com/sayem314/Caddy-Web-Server-Installer/master/caddy.sh -O - -o /dev/null|bash`

**Comment by Nixtren** [comment]
Thanks @sayem314, it's fixed :)

The cat error still shows up, but it's not critical:

``` sh
cat: /var/run/caddy/caddy.pid: No such file or directory
```
